/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./cute.gltf --transform 
Files: ./cute.gltf [7.41MB] > D:\aiml\public\Innov\cute-transformed.glb [169.7KB] (98%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cute-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.geometry_0001.geometry} material={materials['New Material']} />
    </group>
  )
}

useGLTF.preload('/cute-transformed.glb')
