export const events = [
    {
      id: "1",
      title: "Techlock Holmes",
      name:"Tech Quiz",
      description: "Get ready to unlock the power of AI in our one-of-a-kind Technical Quiz event! Dive into a world where human intelligence meets artificial intelligence, as you tackle thought-provoking questions at the intersection of tech and AI. Join us for a mind-bending journey into the future of technology! . The questionnaire will be based on AI and ML/DS and the quiz will be from an AI based quiz platform unlike the conventional pen - paper method. chatbot, personalized recommendations",
      fee: "Rs.150/team",
      rounds: "2 rounds",
      prizes: "Top 3",
      teamlim: "Teams of 3 members",
      imgurl: require("../assets/images/event posters/TECHLOCK HOLMES.webp"),
      rules: "1. The competition consists of 2 rounds, each lasting one hour. <br> 2. The first round will take place on quiz.com. <br> 3. Participants are required to have a mobile device with internet connectivity. <br> 4. Only shortlisted students from the first round will proceed to the final round. <br> 5. The final round will be a buzzer round. <br> 6. The decision of the event coordinators is final. <br> 7. Sharing answers with others will result in elimination. <br> 8. Participants must remain silent during the quiz."    
    },
    {
        id: "2",
        title: "AI Alchemy",
        name:" Idea Presentation",
        description: "Are you ready to embark on a journey into the future of technology and innovation? Join us for an unforgettable evening of groundbreaking AI ideas and cutting-edge presentations at AI Alchemy: Meet the Alchemists!. Ideas based on AI and ML/DS will be given higher priority.",
        fee: "Rs.150/team",
        rounds: "2 rounds",
        prizes: "Top 3",
        teamlim: "Teams of 3 members",
        imgurl: require("../assets/images/event posters/AI ALCHEMY.webp"),
      },
      {
        id: "3",
        title: "Kimi No Code",
        name: "Coding",
        description: "A unique coding event that gives students a gist of the new technologies of AI and ML. The first round will be the usual one. The second round will be a ML coding round, for which a preface will be given before getting started.",
        fee: "Rs.100/team",
        rounds: "2 rounds",
        prizes: "Top 3",
        teamlim: "Teams of 2 members",
        imgurl: require("../assets/images/event posters/KIMI NO CODE.webp"),
      },
      {
        id: "4",
        title: "Fusion Forum",
        name:"UI/UX",
        description: "Create a mobile application and prototype using Figma.",
        fee: "Rs.100/team",
        rounds: "2 rounds",
        prizes: "Top 3",
        teamlim: "Teams of 2 members",
        imgurl:require("../assets/images/event posters/FUSION FORUM.webp"),
      },
      {
        id: "5",
        title: "Enigma Fest",
        name:"Encoding/decoding",
        description: "Cryptography and AI are a powerful duo in technology these days. To unlock its potential, the participants will be assessed based on decoding encrypted texts. Participants will be using an AI steganography tool to decode information.",
        fee: "Rs.50 or Rs.100/team",
        rounds: "2",
        prizes: "Top 3",
        teamlim: "Solo or Teams of 2 members",
        imgurl:require("../assets/images/event posters/ENIGMA FEST.webp"),
      },
      {
        id: "6",
        title: "IntelleXpo",
        name:"Project Expo",
        description: "IntelleXpo is a prestigious project presentation event that provides a platform for college students to showcase their innovative ideas and projects. It's a dynamic competition that encourages participants to not only present their projects but also demonstrate their creativity and teamwork.",
        fee: "Rs.150/team",
        rounds: "2",
        prizes: "Top 3",
        teamlim: "Teams of 3 members",
        imgurl:require("../assets/images/event posters/INTELLEXPO.webp"),
      },
      {
        id: "7",
        title: "Imprompto",
        name:"Prompt Engineering",
        description: "Generative AI has become a buzzword and the need of the hour in the 21st century. Good prompts yield better results. Prompt engineering is equally important as creating new and amazing AI models. Keeping these in mind, we're excited to set the stage for curious minds to flaunt their creativity with AI tools.",
        fee: "Rs.150/team",
        rounds: "2",
        prizes: "Top 3",
        teamlim: "Teams of 3 members",
        imgurl:require("../assets/images/event posters/IMPROMPTO.webp"),
      },
      {
        id: "8",
        title: "Manifesto Matrix",
        name:"Poster making",
        description: "Embark on a creative journey into the world of artificial intelligence at our upcoming poster-making event, The Future Unveiled: AI in Artistry. This unique and innovative event invites artists, designers, and enthusiasts to explore the intersection of creativity and artificial intelligence through the medium of poster design.",
        fee: "Rs.100/team",
        rounds: "2",
        prizes: "Top 2",
        teamlim: "Teams of 2 members",
        imgurl:require("../assets/images/event posters/MANIFESTO MATRIX.webp"),
      },
      {
        id: "9",
        title: "Cryptic Conundrums",
        name:"Murder Mystery",
        description: "A treasure hunt event (with a twist) to assess the problem-solving and analytical skills of the participants.",
        fee: "Rs.150/team",
        rounds: "2",
        prizes: "Top 3",
        teamlim: "Teams of 3 members",
        imgurl:require("../assets/images/event posters/CRYPTIC CONUNDRUMS.webp"),
      },
  ];